/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bow.glb --typescript --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bow.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.292, 3.467, -4.7]} scale={[1.897, 1.106, 1.106]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane008.geometry} material={materials.CowMaterial} />
        <mesh castShadow receiveShadow geometry={nodes.Plane008_1.geometry} material={materials.CowMaterial2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bow.glb')
